/* tslint:disable */
/* eslint-disable */
/**
 * BBOK Swagger API
 * DND 9th 10조의 Swagger docs 입니다.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface DataResponseFriendsDto
 */
export interface DataResponseFriendsDto {
    /**
     * 
     * @type {FriendsDto}
     * @memberof DataResponseFriendsDto
     */
    'data'?: FriendsDto;
    /**
     * 응답 메시지
     * @type {string}
     * @memberof DataResponseFriendsDto
     */
    'message'?: string;
    /**
     * 응답 코드
     * @type {number}
     * @memberof DataResponseFriendsDto
     */
    'status'?: number;
}
/**
 * 
 * @export
 * @interface FriendDto
 */
export interface FriendDto {
    /**
     * 친구 캐릭터 아이콘 url
     * @type {string}
     * @memberof FriendDto
     */
    'characterUrl'?: string;
    /**
     * 친구 생성 날짜 카운팅
     * @type {number}
     * @memberof FriendDto
     */
    'countingDay'?: number;
    /**
     * 친구 관련 일화 수
     * @type {number}
     * @memberof FriendDto
     */
    'countingDiary'?: number;
    /**
     * 친구 고유 ID
     * @type {number}
     * @memberof FriendDto
     */
    'id'?: number;
    /**
     * 친구 이름
     * @type {string}
     * @memberof FriendDto
     */
    'name'?: string;
    /**
     * 친구 점수
     * @type {number}
     * @memberof FriendDto
     */
    'score'?: number;
    /**
     * 친구 활성화 상태
     * @type {boolean}
     * @memberof FriendDto
     */
    'status'?: boolean;
}
/**
 * 
 * @export
 * @interface FriendsDto
 */
export interface FriendsDto {
    /**
     * 친구 목록
     * @type {Array<FriendDto>}
     * @memberof FriendsDto
     */
    'friends'?: Array<FriendDto>;
}

/**
 * MockApi - axios parameter creator
 * @export
 */
export const MockApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 친구 목록 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFriendsUsingGET: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/friend`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MockApi - functional programming interface
 * @export
 */
export const MockApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MockApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 친구 목록 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFriendsUsingGET(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DataResponseFriendsDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getFriendsUsingGET(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * MockApi - factory interface
 * @export
 */
export const MockApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MockApiFp(configuration)
    return {
        /**
         * 
         * @summary 친구 목록 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFriendsUsingGET(options?: any): AxiosPromise<DataResponseFriendsDto> {
            return localVarFp.getFriendsUsingGET(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MockApi - object-oriented interface
 * @export
 * @class MockApi
 * @extends {BaseAPI}
 */
export class MockApi extends BaseAPI {
    /**
     * 
     * @summary 친구 목록 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MockApi
     */
    public getFriendsUsingGET(options?: AxiosRequestConfig) {
        return MockApiFp(this.configuration).getFriendsUsingGET(options).then((request) => request(this.axios, this.basePath));
    }
}


