name: ci

on:
  push:
    branches: ["main", "develop", "feature/*"]

jobs:
  test:
    name: TypeCheck and Lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: yarn install --frozen-lockfile

      - name: TypeCheck and Lint and test
        run: yarn turbo run type-check lint test
